export const cards = [
  {
    id: 1,
    title: "Web Design Task 1",
    category: "Web Design",
    theme: "orange",
    date: "30.10.23",
    status: "Без статуса",
  },
  {
    id: 2,
    title: "Research Task 1",
    category: "Research",
    theme: "green",
    date: "31.10.23",
    status: "Нужно сделать",
  },
  {
    id: 3,
    title: "Web Design Task 2",
    category: "Web Design",
    theme: "orange",
    date: "01.11.23",
    status: "В работе",
  },
  {
    id: 4,
    title: "Copywriting Task 1",
    category: "Copywriting",
    theme: "purple",
    date: "02.11.23",
    status: "Тестирование",
  },
  {
    id: 5,
    title: "Web Design Task 3",
    category: "Web Design",
    theme: "orange",
    date: "03.11.23",
    status: "Готово",
  },
  {
    id: 6,
    title: "Research Task 2",
    category: "Research",
    theme: "green",
    date: "04.11.23",
    status: "Нужно сделать",
  },
  {
    id: 7,
    title: "Copywriting Task 2",
    category: "Copywriting",
    theme: "purple",
    date: "05.11.23",
    status: "В работе",
  },
  {
    id: 8,
    title: "Web Design Task 4",
    category: "Web Design",
    theme: "orange",
    date: "06.11.23",
    status: "Без статуса",
  },
];
